run-shell "${XDG_CONFIG_HOME}/tmux/bootstrap_tpm"

# enable mouse input
set-option -gq mouse on

set -g default-terminal "xterm-256color"
set -as terminal-features ",xterm-256color:Tc"

# Needed to fix some garbage rgb control characters in windows terminal
set -g escape-time 50
# set -g focus-events off

# This carries the shell to whatever we ran it from
set-option -g default-shell $SHELL

# Vim bindings for everything
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line

# Yanking behaviour
bind-key -T copy-mode-vi y send -X copy-pipe 'xclip -in -selection clipboard'
unbind -T copy-mod-vi MouseDragEnd1Pane
set -g @yank_action 'copy-pipe'

# Colorscheme
set -g @tmux_power_theme 'gold'

# Plugins

# Setting where the plugins are installed
set-environment -g TMUX_PLUGIN_MANAGER_PATH "${XDG_DATA_HOME}/tmux"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible' # Sensible defaults
set -g @plugin 'tmux-plugins/tmux-yank' # yank to system clipboard
set -g @plugin 'tmux-plugins/tmux-resurrect' # Save and restore tmux environment across system restarts
set -g @plugin 'tmux-plugins/tmux-continuum' # automatic restore and continuous saving of tmux env
set -g @plugin 'tmux-plugins/tmux-prefix-highlight' # Highlight when prefix is active
set -g @plugin 'wfxr/tmux-power' # Powerline style statusline

run-shell "${XDG_CONFIG_HOME}/tmux/plugins/tpm/tpm"

# This installs all current plugins
run-shell "${XDG_CONFIG_HOME}/tmux/plugins/tpm/clean_plugins"
run-shell "${XDG_CONFIG_HOME}/tmux/plugins/tpm/bin/install_plugins"
# run-shell "${XDG_CONFIG_HOME}/tmux/plugins/tpm/bin/update_plugins.all"

